name: React CI/CD 
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email ${{secrets.GH_EMAIL}}
        git config --global user.name ${{secrets.GH_USERNAME}}
        git remote set-url origin https://${{secrets.PAT_TOKEN}}@github.com/${{secrets.GH_USERNAME}}/SoS-web.git
        npm run deploy
      env:
         CI: false
